### PR TITLE
Set up test automation for Travis CI server

### PR DESCRIPTION
**Pull request by camstuart**
Since the recent addition of a mocha based test suite,
a CI server is now appropriate.

- Added `.travis.yml` and build status badge to the README
- Updated regex code syntax to pass linting
- Added a script command to `package.json` for running a watch on tests

While developing, please run `npm run test-watch`
for continuous test suite execution when files are changed

Resolves: #24

### CODE REVIEW

**Comment by camstuart** [comment]
@cpetrov I have added node major versions 4, 5 & 6. Are these all the sported version we need to test against?

**Comment by camstuart** [comment]
@irbull @cpetrov @ralfstx All you need to do is add this repo to Travis and the next push should trigger a build, and cause the build status badge to light up

**Comment by cpetrov** [comment]
Thanks for the change!

**Comment by ralfstx** [comment]
Thanks @camstuart!

**Pull request merged**
